name: 月报机器人定时任务

on:
  schedule:
    # 每月17-23日的指定时间自动执行
    # 时区设置为阿根廷布宜诺斯艾利斯时间 (UTC-3)
    # GitHub Actions使用UTC时间，阿根廷时间09:30 = UTC时间12:30
    - cron: '30 12 17-19 * *'  # 每月17-19日 09:30 (阿根廷时间) = 12:30 UTC
    - cron: '31 12 18-22 * *'  # 每月18-22日 09:31 (阿根廷时间) = 12:31 UTC
    - cron: '32 12 23 * *'     # 每月23日 09:32 (阿根廷时间) = 12:32 UTC
    - cron: '0 21 23 * *'      # 每月23日 18:00 (阿根廷时间) = 21:00 UTC
  workflow_dispatch:  # 允许手动触发
    inputs:
      task_type:
        description: '任务类型'
        required: true
        default: 'create_tasks'
        type: choice
        options:
        - create_tasks
        - daily_stats
        - final_reminder
        - final_stats
        - help

jobs:
  monthly-bot:
    runs-on: ubuntu-latest
    
    steps:
    - name: 检出代码
      uses: actions/checkout@v4
      
    - name: 设置Python环境
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: 安装依赖
      run: |
        python -m pip install --upgrade pip
        pip install -r monthly_report_bot_link_pack/requirements_github_actions.txt
        
    - name: 创建配置文件
      run: |
        mkdir -p config
        cat > config/bot_config.json << EOF
        {
          "FEISHU_APP_ID": "${{ secrets.FEISHU_APP_ID }}",
          "FEISHU_APP_SECRET": "${{ secrets.FEISHU_APP_SECRET }}",
          "FEISHU_VERIFICATION_TOKEN": "${{ secrets.FEISHU_VERIFICATION_TOKEN }}",
          "FEISHU_ENCRYPT_KEY": "${{ secrets.FEISHU_ENCRYPT_KEY }}",
          "CHAT_ID": "${{ secrets.CHAT_ID }}",
          "WELCOME_CARD_ID": "${{ secrets.WELCOME_CARD_ID }}",
          "FILE_URL": "${{ secrets.FILE_URL }}",
          "TIMEZONE": "America/Argentina/Buenos_Aires"
        }
        EOF
        
    - name: 执行任务创建 (17-19日)
      if: github.event.schedule == '30 12 17-19 * *' || (github.event_name == 'workflow_dispatch' && github.event.inputs.task_type == 'create_tasks')
      run: |
        cd monthly_report_bot_link_pack
        python -c "
        import sys
        sys.path.append('.')
        from github_actions_bot import create_monthly_tasks
        import json
        import os
        
        # 加载配置
        with open('../config/bot_config.json', 'r') as f:
            config = json.load(f)
        
        # 设置环境变量
        for key, value in config.items():
            os.environ[key] = value
            
        # 执行任务创建
        result = create_monthly_tasks()
        print(f'任务创建结果: {result}')
        "
        
    - name: 执行每日统计 (18-22日)
      if: github.event.schedule == '31 12 18-22 * *' || (github.event_name == 'workflow_dispatch' && github.event.inputs.task_type == 'daily_stats')
      run: |
        cd monthly_report_bot_link_pack
        python -c "
        import sys
        sys.path.append('.')
        from github_actions_bot import send_daily_stats
        import json
        import os
        
        # 加载配置
        with open('../config/bot_config.json', 'r') as f:
            config = json.load(f)
        
        # 设置环境变量
        for key, value in config.items():
            os.environ[key] = value
            
        # 执行每日统计
        result = send_daily_stats()
        print(f'每日统计结果: {result}')
        "
        
    - name: 执行最终提醒 (23日)
      if: github.event.schedule == '32 12 23 * *' || (github.event_name == 'workflow_dispatch' && github.event.inputs.task_type == 'final_reminder')
      run: |
        cd monthly_report_bot_link_pack
        python -c "
        import sys
        sys.path.append('.')
        from github_actions_bot import send_final_reminder
        import json
        import os
        
        # 加载配置
        with open('../config/bot_config.json', 'r') as f:
            config = json.load(f)
        
        # 设置环境变量
        for key, value in config.items():
            os.environ[key] = value
            
        # 执行最终提醒
        result = send_final_reminder()
        print(f'最终提醒结果: {result}')
        "
        
    - name: 发送最终统计 (23日)
      if: github.event.schedule == '0 21 23 * *' || (github.event_name == 'workflow_dispatch' && github.event.inputs.task_type == 'final_stats')
      run: |
        cd monthly_report_bot_link_pack
        python -c "
        import sys
        sys.path.append('.')
        from github_actions_bot import send_final_stats
        import json
        import os
        
        # 加载配置
        with open('../config/bot_config.json', 'r') as f:
            config = json.load(f)
        
        # 设置环境变量
        for key, value in config.items():
            os.environ[key] = value
            
        # 执行最终统计
        result = send_final_stats()
        print(f'最终统计结果: {result}')
        "
        
    - name: 发送帮助信息
      if: github.event_name == 'workflow_dispatch' && github.event.inputs.task_type == 'help'
      run: |
        cd monthly_report_bot_link_pack
        python -c "
        import sys
        sys.path.append('.')
        from github_actions_bot import send_help_message
        import json
        import os
        
        # 加载配置
        with open('../config/bot_config.json', 'r') as f:
            config = json.load(f)
        
        # 设置环境变量
        for key, value in config.items():
            os.environ[key] = value
            
        # 发送帮助信息
        result = send_help_message()
        print(f'帮助信息发送结果: {result}')
        "
        
    - name: 发送执行结果通知
      if: always()
      run: |
        echo "任务执行完成，时间: $(date)"
        echo "GitHub Actions URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
